import { PrismaClient } from '@prisma/client';

export default async function seedCouriers(prisma: PrismaClient) {
  console.log('Seeding couriers...');
  const couriers = [
    {
      courier_code: 'gojek',
      courier_service_name: 'Same Day',
      courier_service_code: 'same_day',
      description: 'On Demand within 8 hours (bike)',
      tier: 'premium',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'Gojek',
      service_type: 'same_day',
      shipping_type: 'parcel',
      shipment_duration_range: '6 - 8',
      shipment_duration_unit: 'hours',
    },
    {
      courier_code: 'grab',
      courier_service_name: 'Same Day',
      courier_service_code: 'same_day',
      description: 'On Demand within 8 hours (bike)',
      tier: 'premium',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'Grab',
      service_type: 'Same Day',
      shipping_type: 'parcel',
      shipment_duration_range: '6 - 8',
      shipment_duration_unit: 'hours',
    },
    {
      courier_code: 'jne',
      courier_service_name: 'Reguler',
      courier_service_code: 'reg',
      description: 'Regular service',
      tier: 'free',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'JNE',
      service_type: 'standard',
      shipping_type: 'parcel',
      shipment_duration_range: '2 - 3',
      shipment_duration_unit: 'days',
    },
    {
      courier_code: 'jne',
      courier_service_name: 'YES',
      courier_service_code: 'yes',
      description: 'Express, next day',
      tier: 'essentials',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'JNE',
      service_type: 'overnight',
      shipping_type: 'parcel',
      shipment_duration_range: '1',
      shipment_duration_unit: 'days',
    },
    {
      courier_code: 'jne',
      courier_service_name: 'OKE',
      courier_service_code: 'oke',
      description: 'Economy service',
      tier: 'free',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'JNE',
      service_type: 'standard',
      shipping_type: 'parcel',
      shipment_duration_range: '3 - 4',
      shipment_duration_unit: 'days',
    },
    {
      courier_code: 'jne',
      courier_service_name: 'JTR',
      courier_service_code: 'jtr',
      description: 'Trucking with minimum weight of 10 kg',
      tier: 'premium',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'JNE',
      service_type: 'standard',
      shipping_type: 'freight',
      shipment_duration_range: '3 - 4',
      shipment_duration_unit: 'days',
    },
    {
      courier_code: 'sicepat',
      courier_service_name: 'Reguler',
      courier_service_code: 'reg',
      description: 'Layanan reguler',
      tier: 'free',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'SiCepat',
      service_type: 'standard',
      shipping_type: 'parcel',
      shipment_duration_range: '2 - 3',
      shipment_duration_unit: 'days',
    },
    {
      courier_code: 'sicepat',
      courier_service_name: 'Best',
      courier_service_code: 'best',
      description: 'Besok sampai tujuan',
      tier: 'essentials',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'SiCepat',
      service_type: 'overnight',
      shipping_type: 'parcel',
      shipment_duration_range: '1',
      shipment_duration_unit: 'days',
    },
    {
      courier_code: 'sicepat',
      courier_service_name: 'SDS',
      courier_service_code: 'sds',
      description: 'Same day service',
      tier: 'standard',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'SiCepat',
      service_type: 'same_day',
      shipping_type: 'parcel',
      shipment_duration_range: '1',
      shipment_duration_unit: 'days',
    },
    {
      courier_code: 'sicepat',
      courier_service_name: 'GOKIL',
      courier_service_code: 'gokil',
      description: 'Layanan kargo',
      tier: 'premium',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'SiCepat',
      service_type: 'standard',
      shipping_type: 'freight',
      shipment_duration_range: '3 - 4',
      shipment_duration_unit: 'days',
    },
    {
      courier_code: 'jnt',
      courier_service_name: 'EZ',
      courier_service_code: 'ez',
      description: 'Layanan reguler',
      tier: 'free',
      available_collection_method: ['pickup'],
      available_for_cash_on_delivery: false,
      available_for_proof_of_delivery: false,
      available_for_instant_waybill_id: true,
      courier_name: 'J&T',
      service_type: 'standard',
      shipping_type: 'parcel',
      shipment_duration_range: '2 - 3',
      shipment_duration_unit: 'days',
    },
  ];

  for (const courier of couriers) {
    await prisma.couriers.upsert({
      where: {
        courier_code_courier_service_code: {
          courier_code: courier.courier_code,
          courier_service_code: courier.courier_service_code,
        },
      },
      update: {},
      create: courier,
    });
  }

  console.log('Seed data for couriers added successfully.');
}
